"""Load demo tickets directly into DB (bypasses AI triage for speed)."""
import asyncio
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'backend'))

from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from models.ticket import Ticket
from database import Base

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+asyncpg://nava:nava_dev@localhost:5432/nava"
)

DEMO_TICKETS = [
    {
        "source": "email",
        "sender_name": "Jan Kowalski",
        "sender_email": "jan.kowalski@gmail.com",
        "sender_type": "resident",
        "subject": "Zepsuta brama — pilne",
        "body_raw": "Brama do garażu podziemnego jest otwarta od 3 dni. Może wejść każdy. Dwa razy dzwoniłem, brak odpowiedzi.",
        "priority": "high",
        "category": "maintenance",
        "status": "new",
        "ai_summary": "Brama garażu podziemnego otwarta od 3 dni — zagrożenie bezpieczeństwa.",
        "ai_suggested_action": "Wezwij serwis naprawy bram i zablokuj wejście tymczasowo.",
        "ai_reasoning": "Niezabezpieczony dostęp do budynku stanowi zagrożenie dla mieszkańców.",
        "ai_draft_reply": "Dzień dobry Panie Janie,\n\nDziękujemy za zgłoszenie. Zlecamy naprawę bramy w trybie pilnym. Wrócimy z potwierdzeniem terminu.\n\nZ poważaniem",
    },
    {
        "source": "sms",
        "sender_name": "+48 601 234 567",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "Hej, przecieka sufit na klatce schodowej 3. piętro, robi się coraz gorzej",
        "priority": "high",
        "category": "maintenance",
        "status": "new",
        "ai_summary": "Przeciek sufitu na klatce schodowej 3. piętra — narastający problem.",
        "ai_suggested_action": "Wyślij technika na oględziny i ustal źródło przecieku.",
        "ai_reasoning": "Przeciek może prowadzić do poważniejszych uszkodzeń konstrukcji i instalacji.",
        "ai_draft_reply": "Dziękujemy za zgłoszenie. Wysyłamy technika na klatke schodową 3. piętro. Skontaktujemy się wkrótce.",
    },
    {
        "source": "email",
        "sender_name": "M. Wiśniewska",
        "sender_email": "m.wisniewska@wp.pl",
        "sender_type": "resident",
        "subject": "Brak rozliczenia za marzec",
        "body_raw": "Ani ja, ani sąsiadka z 14B nie dostałyśmy rozliczenia za marzec. Proszę o przesłanie.",
        "priority": "medium",
        "category": "inquiry",
        "status": "new",
        "ai_summary": "Brak rozliczenia za marzec dla co najmniej dwóch mieszkań — prośba o wysłanie dokumentów.",
        "ai_suggested_action": "Wyślij rozliczenia za marzec do nadawczyni i mieszkania 14B.",
        "ai_reasoning": "Standardowe zapytanie administracyjne, nie wymaga pilnej interwencji.",
        "ai_draft_reply": "Dzień dobry,\n\nPrzepraszamy za opóźnienie. Rozliczenie za marzec zostanie przesłane na Państwa adresy do jutra.\n\nZ poważaniem",
    },
    {
        "source": "sms",
        "sender_name": "+48 799 112 233",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "Mieszkanie 4B znowu wynajmuje na Airbnb. To jest niezgodne z regulaminem wspólnoty. Co z tym będziecie robić?",
        "priority": "medium",
        "category": "complaint",
        "status": "new",
        "ai_summary": "Skarga na nielegalne wynajmowanie mieszkania 4B przez Airbnb — naruszenie regulaminu.",
        "ai_suggested_action": "Wyślij pismo do właściciela mieszkania 4B z przypomnieniem o regulaminie.",
        "ai_reasoning": "Naruszenie regulaminu wspólnoty wymaga formalnej reakcji, ale nie jest pilne.",
        "ai_draft_reply": "Dziękujemy za informację. Zbadamy sprawę mieszkania 4B i podejmiemy stosowne kroki zgodnie z regulaminem wspólnoty.",
    },
    {
        "source": "email",
        "sender_name": "Zarząd Wspólnoty",
        "sender_email": "zarzad@wspolnota-mokotow.pl",
        "sender_type": "board",
        "subject": "Decyzja zarządu — remont dachu",
        "body_raw": "Otrzymaliśmy trzy oferty na remont dachu. Zarząd musi podjąć decyzję przed kwietniowym zebraniem. Proszę o podsumowanie i rekomendację.",
        "priority": "high",
        "category": "inquiry",
        "status": "new",
        "ai_summary": "Zarząd prosi o analizę trzech ofert na remont dachu przed zebraniem w kwietniu.",
        "ai_suggested_action": "Przygotuj zestawienie ofert z rekomendacją dla zarządu.",
        "ai_reasoning": "Decyzja strategiczna z konkretnym terminem — wysoki priorytet.",
        "ai_draft_reply": "Dzień dobry,\n\nPrzygotujemy podsumowanie i rekomendację dotyczącą ofert na remont dachu przed zebraniem. Możemy oczekiwać gotowego materiału do końca tygodnia.\n\nZ poważaniem",
    },
    {
        "source": "sms",
        "sender_name": "+48 512 887 001",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "Pani Ania nie odpowiada od tygodnia na moje maile w sprawie funduszu remontowego",
        "priority": "medium",
        "category": "inquiry",
        "status": "new",
        "ai_summary": "Mieszkaniec zgłasza brak odpowiedzi od administratora przez tydzień w sprawie funduszu remontowego.",
        "ai_suggested_action": "Skontaktuj się z nadawcą i wyjaśnij sprawę funduszu remontowego.",
        "ai_reasoning": "Brak odpowiedzi przez tydzień wymaga reakcji — ryzyko eskalacji niezadowolenia.",
        "ai_draft_reply": "Dzień dobry,\n\nPrzepraszamy za brak odpowiedzi. Skontaktujemy się z Państwem w sprawie funduszu remontowego do końca dnia.\n\nZ poważaniem",
    },
    {
        "source": "email",
        "sender_name": "P. Nowak",
        "sender_email": "p.nowak@gmail.com",
        "sender_type": "resident",
        "subject": "Skargi na hałas — mieszkanie 12A",
        "body_raw": "To już czwarta skarga na to mieszkanie. Głośna muzyka każdą noc po północy. Nic nie zostało zrobione.",
        "priority": "high",
        "category": "complaint",
        "status": "new",
        "follow_up_count": 3,
        "escalated": True,
        "ai_summary": "Czwarta skarga na hałas z mieszkania 12A — głośna muzyka nocna, brak dotychczasowej reakcji.",
        "ai_suggested_action": "Wyślij formalne ostrzeżenie do właściciela mieszkania 12A.",
        "ai_reasoning": "Czwarta skarga na ten sam problem bez rozwiązania — eskalacja obowiązkowa.",
        "ai_draft_reply": "Dzień dobry,\n\nDziękujemy za kolejne zgłoszenie. Rozumiemy frustrację. Wysyłamy formalne upomnienie do mieszkania 12A i informujemy o konsekwencjach dalszego naruszania regulaminu.\n\nZ poważaniem",
        "admin_notes": "\n[SYSTEM] Auto-escalated: 4 follow-ups detected",
    },
    {
        "source": "sms",
        "sender_name": "+48 604 332 119",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "Winda znowu zepsuta w budynku B. Trzeci raz w tym miesiącu.",
        "priority": "high",
        "category": "maintenance",
        "status": "new",
        "ai_summary": "Winda w budynku B niesprawna — trzecia awaria w miesiącu.",
        "ai_suggested_action": "Wezwij serwis windowy i rozważ umowę serwisową.",
        "ai_reasoning": "Częste awarie wskazują na potrzebę przeglądu technicznego lub wymiany komponentów.",
        "ai_draft_reply": "Dziękujemy za zgłoszenie. Wzywamy serwis windowy. Rozważymy umowę serwisową ze względu na częste awarie.",
    },
    {
        "source": "email",
        "sender_name": "R. Dąbrowska",
        "sender_email": "r.dabrowska@onet.pl",
        "sender_type": "resident",
        "subject": "Odnowienie ubezpieczenia",
        "body_raw": "Ubezpieczenie budynku kończy się 30 kwietnia. Nie widzę tego w agendzie zebrania. Kto się tym zajmuje?",
        "priority": "high",
        "category": "inquiry",
        "status": "new",
        "ai_summary": "Ubezpieczenie budynku wygasa 30 kwietnia — brak tego punktu w agendzie zebrania.",
        "ai_suggested_action": "Dodaj odnowienie ubezpieczenia do agendy zebrania i skontaktuj się z ubezpieczycielem.",
        "ai_reasoning": "Termin wygaśnięcia ubezpieczenia jest bliski — wymaga pilnego działania.",
        "ai_draft_reply": "Dzień dobry,\n\nDziękujemy za zwrócenie uwagi. Dodajemy ten punkt do agendy i zajmiemy się odnowieniem ubezpieczenia przed 30 kwietnia.\n\nZ poważaniem",
    },
    {
        "source": "sms",
        "sender_name": "+48 733 201 445",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "Czy ktoś może potwierdzić, że moja wpłata na fundusz eksploatacyjny dotarła? Zapłaciłem 3 tygodnie temu.",
        "priority": "low",
        "category": "inquiry",
        "status": "new",
        "ai_summary": "Prośba o potwierdzenie wpłaty na fundusz eksploatacyjny sprzed 3 tygodni.",
        "ai_suggested_action": "Sprawdź w systemie wpłatę i potwierdź mieszkańcowi.",
        "ai_reasoning": "Standardowe zapytanie finansowe — niski priorytet, ale wymaga odpowiedzi.",
        "ai_draft_reply": "Dzień dobry,\n\nSprawdzimy status Pana wpłaty i potwierdzimy w ciągu 24 godzin.\n\nZ poważaniem",
    },
    {
        "source": "email",
        "sender_name": "Jan Kowalski",
        "sender_email": "jan.kowalski@gmail.com",
        "sender_type": "resident",
        "subject": "RE: Zepsuta brama",
        "body_raw": "Piszę PO RAZ TRZECI. Brama nadal otwarta. Jeśli do końca tygodnia nic się nie zmieni, zgłaszam sprawę do nadzoru budowlanego.",
        "priority": "critical",
        "category": "maintenance",
        "status": "new",
        "follow_up_count": 2,
        "escalated": True,
        "ai_summary": "Trzecia wiadomość w sprawie otwartej bramy garażowej — mieszkaniec grozi zgłoszeniem do nadzoru budowlanego.",
        "ai_suggested_action": "Natychmiast zadzwoń do Jana Kowalskiego i wyślij ekipę do bramy.",
        "ai_reasoning": "Groźba zgłoszenia do nadzoru budowlanego wymaga natychmiastowej reakcji.",
        "ai_draft_reply": "Dzień dobry Panie Janie,\n\nPrzepraszamy za brak reakcji. Wysyłamy ekipę do bramy garażowej dziś. Skontaktujemy się z Panem telefonicznie w ciągu godziny.\n\nZ poważaniem",
        "admin_notes": "\n[SYSTEM] Auto-escalated: 3 follow-ups detected",
    },
    {
        "source": "sms",
        "sender_name": "+48 601 234 567",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "O tej przeciekającej klatce schodowej co pisałem — teraz leje się na skrzynkę elektryczną. To chyba groźne?",
        "priority": "critical",
        "category": "maintenance",
        "status": "new",
        "escalated": True,
        "ai_summary": "Przeciek na klatce schodowej dotarł do skrzynki elektrycznej — zagrożenie pożarowe i porażeniem prądem.",
        "ai_suggested_action": "Natychmiast wyłącz prąd w zagrożonej sekcji i wezwij elektryka oraz hydraulika.",
        "ai_reasoning": "Woda w pobliżu instalacji elektrycznej stanowi bezpośrednie zagrożenie życia.",
        "ai_draft_reply": "To jest pilna sytuacja bezpieczeństwa. Wysyłamy ekipę natychmiast. Proszę nie dotykać skrzynki elektrycznej i ostrzec sąsiadów.",
        "admin_notes": "\n[SYSTEM] Auto-escalated: water+electrical hazard",
    },
    {
        "source": "voicemail",
        "sender_name": "+48 888 100 200",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "[Transkrypcja Whisper, pewność ~72%] Dzień dobry, dzwonię... chyba Lewandowska z... [nieczytelne]... bo proszę pani, w piwnicy jest woda na... nie wiem... dwadzieścia centymetrów? Może więcej. I śmierdzi. Proszę o... [nieczytelne]... jak najszybciej.",
        "priority": "critical",
        "category": "maintenance",
        "status": "new",
        "escalated": True,
        "ai_summary": "Prawdopodobnie Lewandowska zgłasza zalanie piwnicy wodą (~20 cm) z nieprzyjemnym zapachem.",
        "ai_suggested_action": "Natychmiast wyślij ekipę do piwnicy i oddzwoń pod +48 888 100 200.",
        "ai_reasoning": "Zalanie piwnicy z zapachem może oznaczać awarię kanalizacji — krytyczne zagrożenie sanitarne.",
        "ai_draft_reply": "Dzień dobry,\n\nOddzwaniamy w związku z Pani wiadomością. Wysyłamy ekipę do piwnicy natychmiast. Proszę o kontakt pod numer zarządcy.\n\nZ poważaniem",
        "admin_notes": "\n[SYSTEM] Auto-escalated: flooding + odor = likely sewage",
    },
    {
        "source": "email",
        "sender_name": "Bud-Serwis",
        "sender_email": "biuro@bud-serwis.pl",
        "sender_type": "vendor",
        "subject": "Faktura nr FS/2024/0892",
        "body_raw": "W załączniku przesyłam fakturę za przegląd instalacji gazowej (budynki A–C). Kwota 8.200 zł netto. Proszę o potwierdzenie lub zgłoszenie korekt w ciągu 7 dni roboczych.",
        "priority": "medium",
        "category": "vendor",
        "status": "new",
        "ai_summary": "Faktura za przegląd instalacji gazowej budynków A–C na kwotę 8 200 zł netto — termin odpowiedzi 7 dni.",
        "ai_suggested_action": "Zweryfikuj fakturę FS/2024/0892 w systemie księgowym i potwierdź lub zgłoś korekty.",
        "ai_reasoning": "Standardowa faktura od dostawcy z określonym terminem odpowiedzi.",
        "ai_draft_reply": "Dzień dobry,\n\nPotwierdzamy odbiór faktury FS/2024/0892. Przekazujemy do działu finansowego. Odpowiemy w ciągu 7 dni roboczych.\n\nZ poważaniem",
    },
    {
        "source": "email",
        "sender_name": "Tomek Zielinski",
        "sender_email": "tomek.zielinski@outlook.com",
        "sender_type": "resident",
        "subject": "Quick question about the parking spot",
        "body_raw": "Hi, I just moved in (apt 7C) and my Polish is still not great. Is there a way to rent an additional parking spot in the garage? Also the intercom doesn't seem to work for my unit. Thanks!",
        "priority": "medium",
        "category": "inquiry",
        "status": "new",
        "ai_summary": "New resident (apt 7C) asks about renting additional parking and reports broken intercom.",
        "ai_suggested_action": "Reply in English: explain parking rental process and send a technician to fix intercom in 7C.",
        "ai_reasoning": "Two separate issues — parking inquiry (routine) and broken intercom (maintenance). English reply needed.",
        "ai_draft_reply": "Hi Tomek,\n\nWelcome to the building! Yes, additional parking spots can be rented — please contact our office to check availability. We'll also send a technician to fix the intercom in apartment 7C.\n\nBest regards",
    },
    {
        "source": "sms",
        "sender_name": "+48 606 999 111",
        "sender_type": "resident",
        "subject": None,
        "body_raw": "Cześć, z tego co wiem to pani z 8A też ma zalany sufit, chyba ten sam problem co u mnie na 3 piętrze. Może warto sprawdzić całą pionówkę?",
        "priority": "high",
        "category": "maintenance",
        "status": "new",
        "ai_summary": "Mieszkaniec sugeruje, że przeciek sufitu obejmuje całą pionówkę — przynajmniej mieszkania na 3. piętrze i 8A.",
        "ai_suggested_action": "Zlec inspekcję całej pionówki instalacji wodnej.",
        "ai_reasoning": "Jeśli przeciek dotyczy wielu mieszkań, wymaga to systemowej naprawy, nie tylko punktowej.",
        "ai_draft_reply": "Dziękujemy za informację. Zlecamy inspekcję całej pionówki w celu zdiagnozowania źródła problemu.",
    },
]


async def seed():
    engine = create_async_engine(DATABASE_URL, echo=False)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    async with session_factory() as session:
        for data in DEMO_TICKETS:
            ticket = Ticket(**data)
            session.add(ticket)
        await session.commit()

    print(f"✓ Inserted {len(DEMO_TICKETS)} demo tickets.")
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
